# -*- coding: utf-8 -*-
"""nlp-sentiment-analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6rJZkvSqqo-Y5tdLSmSFrovDErfyw_D

# NLP Essentials Project

# Sentiment Analysis Online Movie Reviews

### Project Scenario

In a recent [market research](https://newsroom.ibm.com/IBMs-Global-AI-Adoption-Index-2021?lnk=ushpv18ai3) by IBM, almost one-third of IT professionals surveyed globally say their business is using Artificial Intelligence (AI). The survey reported almost half of businesses today are now using applications powered by natural language processing (NLP).

NLP, specifically 'Sentiment Analysis', can provide a key business advantage by abstracting from unstructured text data the negative or positive attitude of the writer/author. This crucuial insight can help turn web data into market intelligence for the business.

A request has been received from the web development department to add 'Sentiment Analysis' feature to a movie reviews page.

The insights from the sentiment analysis will be used to promote more popular movies.  

In this project, you are tasked to create a prototype NLP project that is capable of 'Sentiment Analysis' from movie reviews.

---

In this assignment, you will be working **individually** on the 'Sentiment Analysis' project.

Complete ALL THE TASKS ( From 1 to 7). You may refer to online documentation (e.g. keras, pandas, etc) for help on syntax.

`No copying of codes wholesale is allowed.`

Use a random_state = 42 where appropriate.

Broadly, this project will require the following steps:

1. Importing Various Modules.
1.Problem scoping.
>1.1. Defining problem statement using 4Ws (Who, What, Where, Why) problem canvas from the project scenario.

2.Data acquisition and Data exploration.
>2.1.Importing various modules.

>2.2.Preparing the data.

>>2.2.1. Preprocess Text.

>>2.2.2. Perform image pre-processing and data augmentation.

>>2.2.3.Split it into train, validate, and test datasets.

>>2.2.4. Perform Feature Extraction Using TF-IDF.

3.Modelling.

>3.1. Create the model - Build a model based on Build a model based on Neural Network.

# Part 1 : Data loading and preliminary inspection

The data for this project will be from `polarity dataset 2.0` collected by [Bo Pang and colleagues from Cornell Univeristy](http://www.cs.cornell.edu/people/pabo/movie-review-data/).

*(This dataset will be provided to you.)*

It was used for the paper published in 2002 called Thumbs up?
Sentiment Classification using Machine Learning Techniques, by Bo Pang, Lilian Lee, and Shivakumar Vaithyanathan.


Using google colab, load the given dataset according the folder structure.
"""

from google.colab import drive
drive.mount('/content/drive/')

path='/content/drive/MyDrive/ITE/NLP /Project'

import os
print(os.listdir(path))

"""### Folder Structure
**Reminder**

In your google drive folder ensure you have the following directory structure set up:
```
Directory Structure In Google Drive:
MyDrive
|
+-- ITE
     |
     +--NLP
        |
        +--Project
          |
          +data
              |
              +--pos
              |
              +--neg
         
```

## Task 2: Data acquisition and Data exploration.

Collect an additional 30 samples of positive reviews and 30 samples of negative reviews from this website:
https://www.rottentomatoes.com/browse/movies_in_theaters/sort:newest?page=1


Add these to the given dataset respectively.

The final dataset should have 1000 positive reviews and 1000 negative reviews.
"""

#@markdown { "tags": "hide-ouput" }

import matplotlib.pyplot as plt
f, ax=plt.subplots(1,2, figsize=(20,20))
pic_name1 = path+"/ReviewsScreenCapture.jpg"
pic_name2=path+"/MoviesPage.jpg"

ax[1].title.set_text("From the movie page, scroll down to see the critic reviews. \nSelect the positive or negative reviews.")
ax[1].imshow(plt.imread(pic_name1))

ax[0].title.set_text("Scroll through the movie page and select any movies.")
ax[0].imshow(plt.imread(pic_name2))
plt.axis('off')

# The following codes in this cell are provided as a guide.

import os

def read_in(folder):
    files = os.listdir(folder)
    a_dict = {}
    for a_file in sorted(files):
        if not a_file.startswith("."):
            with open(folder + a_file, encoding='ISO-8859-1', errors ='ignore') as f:
                file_id = a_file.split(".")[0].strip()
                a_dict[file_id] = f.read()
            f.close()
    return a_dict

"""Print out the number of reviews in positive and negative dictionaries, as well as the very first positive and very first negative reviews in the dictionaries."""

print(os.listdir(path + "/data/pos"))

def read_in(folder):
    a_dict = {}                          # empty dictionary to store results
    files = os.listdir(folder)           # get list of all files in the folder
    for a_file in sorted(files):         # loop through files in alphabetical order
        if not a_file.startswith("."):   # skip hidden files (e.g. .DS_Store)
            with open(os.path.join(folder, a_file), encoding='ISO-8859-1', errors='ignore') as f:
                                         # open each file safely
                file_id = a_file.split(".")[0].strip()  # use filename (without extension) as key
                                                         # e.g. "cv000_29590.txt" → "cv000_29590"
                a_dict[file_id] = f.read()  # store the file's text content as the value
    return a_dict                        # return the completed dictionary

# The following codes in this cell are provided as a guide

folder=path+'/data/'
pos_dict = read_in(folder + "pos")
print(len(pos_dict))
print(pos_dict.get(next(iter(pos_dict))))
neg_dict = read_in(folder + "neg")
print(len(neg_dict))
print(neg_dict.get(next(iter(neg_dict))))

"""## Task 2.1: Importing various modules - Data Cleansing

Import the relevant NLTK libraries.
"""

# The following codes in this cell are provided as a guide

import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

"""### Task 2.1: Importing various modules - Add More Stops Words To NLTK

Add the following to stopwords:
1. '@'
2. '#'
3. 'http'
4. ':'
"""

stop = nltk.corpus.stopwords.words('english')
# Add a few more stop words we would like to remove here
stop.extend(['@', '#', 'http', ':'])

"""### Task 2.2.2 : Process Text - Tokenize, Remove Punctuation, Lemmatize

Complete the following functions.
"""

import string

# tokenize text using nltk
def tokenize(text):
    return nltk.word_tokenize(text)

# remove punctuation from text using 'string.punctuation'
def remove_punctuation(text):
    return [word for word in text if word not in string.punctuation]

# lemmatize sentence using 'nltk.stem.PorterStemmer'
def lemmatize(sentence):
    porter = nltk.stem.PorterStemmer()
    return [porter.stem(word) for word in sentence]

def process_text(text):
    tokenized_text = tokenize(text)
    tokenized_text = remove_punctuation(tokenized_text)
    lemmas = lemmatize(tokenized_text)
    processed = [w.lower() for w in lemmas if w not in stop]
    return processed

"""## Task 3: Randomly Combine Review Texts From Positive & Negative Reviews Data Sets.

Preprocessed texts to remove punctuation, remove stop words andlemmatized the text.

Combine all these texts into a single dataset where each preprocessed review and its label are in a tuple:

`data=[('preprocessed review text', label), ('preprocessed review text', label) ...]`

**Example:**

* ('this movie is nice', 1)
* ('this movie is lousy',0)

Label for positive and negative review:
* `Positive review is given 1.`
* `Negative review is given 0.`

"""

import random
from tqdm import tqdm
nltk.download('punkt_tab')

def prepare_data(pos_dict, neg_dict):
    data = []
    originalText = []

    for each_dict, label in [(pos_dict, 1), (neg_dict, 0)]:  # pair dicts with labels

        for id in tqdm(each_dict, desc='Reviews Progressed Bar'):
            text = each_dict[id]
            originalText.append(text)                        # store original raw text
            processed = process_text(text)                   # preprocess the text
            data.append((' '.join(processed), label))        # store preprocessed text + label

    random.seed(42)
    random.shuffle(data)

    texts = []
    labels = []
    for item in data:
        texts.append(item[0])
        labels.append(item[1])

    return originalText, texts, labels

originalText, texts, labels = prepare_data(pos_dict, neg_dict)

print(len(texts), len(labels))
print(texts[0])

"""### Task 2.2.3: Split Dataset Into Train Test Sets.

Split the texts into:

1. 80% for training.
2. 20% for testing.
"""

def split(texts, labels, proportion):
    train_data = []
    train_targets = []
    test_data = []
    test_targets = []

    split_index = int(len(texts) * proportion)  # calculate where to split (80%)

    train_data = texts[:split_index]            # first 80% for training
    train_targets = labels[:split_index]
    test_data = texts[split_index:]             # remaining 20% for testing
    test_targets = labels[split_index:]

    return train_data, train_targets, test_data, test_targets

train_data, train_targets, test_data, test_targets = split(texts, labels, 0.8)

print(len(train_data))       # 1512
print(len(train_targets))    # 1512
print(len(test_data))        # 378
print(len(test_targets))     # 378
print(train_targets[:10])
print(test_targets[:10])

# The following codes in this cell are provided as a guide

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

print(len(train_data))
print(train_data[0])  # print first review to see if it has text

print(len(pos_dict))
print(len(neg_dict))

# The following codes in this cell are provided as a guide

count_vect = CountVectorizer(analyzer = "word", strip_accents=None, tokenizer = None, \
                             preprocessor = None, stop_words = None, max_features = 500)


train_data_features = count_vect.fit_transform(train_data)
test_data_features = count_vect.transform(test_data)

# Check the dimensionality
print(train_data_features.shape)
print(test_data_features.shape)

"""The max features for CountVectorizer function has been set to 500. The parameter can be adjusted to improve results."""

print(train_data_features[:11])

count_vect.get_feature_names_out()[321]

"""# Part 2: Perform AI Natural Language Inference

## Task 2.2.4: Feature Extraction Using TF-IDF

Perform normalization of bag of words using the TfidfTransformer. Use it the same way as above.

Create a class, and use the .fit_transform() method with the bag of words as your argument to create your TFIDF.
"""

tfidfier = TfidfTransformer()
tfidf = tfidfier.fit_transform(train_data_features)
tfidf_test = tfidfier.transform(test_data_features)

print(tfidf.shape)       # should be (1512, 500)
print(tfidf_test.shape)  # should be (378, 500)

# The following codes in this cell are provided as a guide

import numpy as np
X_train = tfidf.toarray()
y_train = np.array(train_targets.copy())
X_test = tfidf_test.toarray()
y_test = np.array(test_targets.copy())

# The following codes in this cell are provided as a guide
# Convert a vector with integers representing different categories
# into binary form: [0,1,0,0 ... ]

from tensorflow.keras.utils import to_categorical
import numpy as np

y_train = to_categorical(y_train - y_train.min())
y_test = to_categorical(y_test - y_test.min())

print(y_train.shape)
print(y_test.shape)

#The dtype="int8" in the original just specified the data type of the output array, which is a minor memory optimization and doesn't affect the actual conversion. The new code produces the same one-hot encoded result, just with the default float32 dtype instead.

y_train[0]

np.unique(y_train[:,1], return_counts=True)

y_test[-10:]

"""## Task 5: Create Model Using Neural Networks

Create a suitable neural network and train it.

"""

from keras.models import Sequential
from keras.losses import sparse_categorical_crossentropy
from keras.losses import categorical_crossentropy
from keras.losses import binary_crossentropy
from tensorflow.keras.optimizers import SGD
from keras.layers import Dense


model = Sequential()

model.add(Dense(256,
                input_dim=500,
                activation='relu'))

model.add(Dense(2,
                activation='softmax'))

model.compile(loss=categorical_crossentropy,
              optimizer=SGD(learning_rate=0.01),
              metrics=['accuracy'])

history=model.fit(tfidf.toarray(), y_train,
          validation_data=(tfidf_test.toarray(), y_test),
          epochs=100,
          verbose=1)

import numpy as np

# Reset labels from the original split
y_train = np.array(train_targets)
y_test = np.array(test_targets)

# Apply to_categorical only once
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train - y_train.min())
y_test = to_categorical(y_test - y_test.min())

print(y_train.shape)  # should be (1512, 2)
print(y_test.shape)   # should be (378, 2)

num_epochs = 100

def plot_graphs(H, metric):
  plt.style.use("ggplot")
  plt.figure()
  plt.plot(np.arange(0, num_epochs), H.history["loss"], label="train_loss")
  plt.plot(np.arange(0, num_epochs), H.history["val_loss"], label="val_loss")
  plt.plot(np.arange(0, num_epochs), H.history["accuracy"], label="train_acc")
  plt.plot(np.arange(0, num_epochs), H.history["val_accuracy"], label="val_acc")
  plt.title("Training Loss and Accuracy")
  plt.xlabel("Epoch #" )
  plt.ylabel("Loss/Accuracy" )
  plt.legend()
  plt.savefig("model history")
  plt.show()

plot_graphs(history, 'acc')

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

predicted = model.predict(X_test)
predicted_label=[np.argmax(each) for each in np.array(predicted)]
y_test_label=[np.argmax(each) for each in np.array(y_test)]
print("\nConfusion matrix:")
print(confusion_matrix(y_test_label, predicted_label))
print(classification_report(y_test_label, predicted_label))

history.history['accuracy']
history.history['val_accuracy']

"""## Task 6: Test For Unseen Text

Use the trained model to make predictions on totally unseen text.
"""

#use the following text for prediction
neg_text="Just when you think you’ve seen the worst movie ever made,\
along comes this pile of toxic waste."

pos_text='This is going to go down as one of 2022’s most entertaining motion pictures.'

def test_model(pos_text, neg_text, tfidfier, model):
  for text in [pos_text, neg_text]:

    processed = ' '.join(process_text(text))

    print("\nNew Text To Predict:\n", "\"" + text + "\"")

    X = tfidfier.transform([processed])

    result = model.predict(X)

    if result[0] == 0:
      print("\nPredicted Sentiment: NEGATIVE")
    else:
      print("\nPredicted Sentiment: POSITIVE")

def test_model(pos_text, neg_text, count_vect, tfidfier, model):
    for text in [pos_text, neg_text]:

        # 1. Preprocess the input text the same way training data was processed
        processed_NewText = ' '.join(process_text(text))

        print("\nNew Text To Predict:\n", "\"" + text + "\"")

        # 2. Vectorize using the fitted CountVectorizer, then apply TF-IDF
        text_for_prediction = tfidfier.transform(
            count_vect.transform([processed_NewText])
        ).toarray()

        # 3. Get model prediction
        result = model.predict(text_for_prediction)

        # 4. result shape is (1, 2) — index 0 = negative, index 1 = positive
        if result[0][0] > result[0][1]:
            print()
            print("Predicted Sentiment: NEGATIVE")
        else:
            print()
            print("Predicted Sentiment: POSITIVE")

test_model(pos_text, neg_text, count_vect, tfidfier, model)

"""## Task 7: Apply Cosine Similarity To Find Similar Texts

Based on the given unseen positive and negative text previously, find the top most similar sentences from the training dataset.

Reminder: Please note that you have to use the same fitted "tfidf" model to perform feature extraction of your texts.
"""

from sklearn.metrics.pairwise import cosine_similarity

neg_text = "Just when you think you've seen the worst movie ever made,\
along comes this pile of toxic waste."

pos_text = "This is going to go down as one of 2022's most entertaining motion pictures."

def findSimiarlTextModel(pos_text, neg_text, count_vect, tfidfier, model):
    for text in [pos_text, neg_text]:

        # 1. Preprocess the new text
        processed_NewText = ' '.join(process_text(text))

        print("\nNew Text To Predict:\n", "\"" + text + "\"")

        # 2. Transform using the SAME fitted count_vect and tfidfier
        t = tfidfier.transform(
            count_vect.transform([processed_NewText])
        )

        # 3. Convert to dense array for cosine similarity
        text_for_prediction = t.toarray()

        # 4. Compare against ALL training documents
        vals = cosine_similarity(text_for_prediction, tfidf.toarray())

        print(vals, type(vals), vals.shape)
        vals = vals.reshape(-1)
        print(vals.argsort()[-1])
        print(vals[vals.argsort()[-1]])
        print(originalText[vals.argsort()[-1]])

findSimiarlTextModel(pos_text, neg_text, count_vect, tfidfier, model)

"""---

**End of Project**

---
"""
